Added Greeting Github Actions
aquasecurity/kube-hunter pull request #382
Opened 2020-10-06 02:11 UTC by anushkrishnav

## Description
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context. List any dependencies that are required for this change.
Every Contributor to an OpenSource Project is special that is why I feel We should add a small GithubAction to give a warm welcome to the contributors.
Added a workflow file in .github folder with a greetings.yml file

## Contribution Guidelines
Please Read through the [Contribution Guidelines](https://github.com/aquasecurity/kube-hunter/blob/master/CONTRIBUTING.md).

## Fixed Issues

Please mention any issues fixed in the PR by referencing it properly in the commit message.
As per the convention, use appropriate keywords such as `fixes`, `closes`, `resolves` to automatically refer the issue.
Please consult [official github documentation](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) for details.

Fixes #(issue)
#381 

## "BEFORE" and "AFTER" output

To verify that the change works as desired, please include an output of terminal before and after the changes under headings "BEFORE" and "AFTER".

### BEFORE
Any Terminal Output Before Changes.

### AFTER
Any Terminal Output Before Changes.

## Contribution checklist
 - [x] I have read the Contributing Guidelines.
 - [x] The commits refer to an active issue in the repository.
 - [ ] I have added automated testing to cover this case.
 
## Notes
Please mention if you have not checked any of the above boxes.

2020-10-19 09:08 UTC, danielsagi commented on .github/workflows/greetings.yml
> +        pr-message: 'Submitted a PR already ?? That's amazing @${{ github.actor }} . Sit tight until one of our amazing maintainers review it. Make sure you read the contributing guide'
You can remove the "amazing" :)

2020-10-19 09:14 UTC, danielsagi requested changes
Nice addition to the project, Just had 2 minor comments

2020-10-19 09:14 UTC, danielsagi commented on .github/workflows/greetings.yml
> +        pr-message: 'Submitted a PR already ?? That's amazing @${{ github.actor }} . Sit tight until one of our amazing maintainers review it. Make sure you read the contributing guide'
You can remove the "amazing" :)

2020-10-19 09:14 UTC, danielsagi commented on .github/workflows/greetings.yml
> +        issue-message: 'Hola! @${{ github.actor }} 🥳, You just created an Issue!🌟 Thanks for making the Project Better and empowering Learners'
Lets do: 
"Hola! @${{ github.actor }} 🥳, You've just created an Issue!🌟 Thanks for making the Project Better"

2020-10-19 09:19 UTC, anushkrishnav commented on .github/workflows/greetings.yml
> +        pr-message: 'Submitted a PR already ?? That's amazing @${{ github.actor }} . Sit tight until one of our amazing maintainers review it. Make sure you read the contributing guide'
Suree

2020-10-19 09:26 UTC, anushkrishnav commented
Can I Contribute it to other projects also?

2020-11-01 14:57 UTC, anushkrishnav commented
please take a look at it @danielsagi

2020-11-07 13:10 UTC, danielsagi approved these changes

2020-11-07 13:16 UTC, merged