Add discovery hunter for AWS metadata
aquasecurity/kube-hunter pull request #447
Opened 2021-04-20 01:42 UTC by jan0ski

## Description
Adds a discovery hunter to identify access to the AWS metadata service.  Has checks for both version 1 and 2 (session based) of the service.

## Contribution Guidelines
Please Read through the [Contribution Guidelines](https://github.com/aquasecurity/kube-hunter/blob/main/CONTRIBUTING.md).

## Fixed Issues

Partially fixes #45 by providing a hunter that identifies access to the AWS instance metadata service versions 1 & 2.

## "BEFORE" and "AFTER" output

### BEFORE
```
$ kubectl apply -f job.yaml
$ kubectl logs job/kube-hunter | grep -v INFO | jq -r '.vulnerabilities | .[] | .vulnerability,.vid'
Read access to pod's service account token
KHV050
Access to pod's secrets
None
CAP_NET_RAW Enabled
None
Access to API using service account token
KHV005
K8s Version Disclosure
KHV002
```

### AFTER
```
$ kubectl apply -f job.yaml
$ kubectl logs job/kube-hunter | grep -v INFO | jq -r '.vulnerabilities | .[] | select(.vid=="KHV053")'
{
  "location": "Local to Pod (kube-hunter-9qfnr)",
  "vid": "KHV053",
  "category": "Information Disclosure",
  "severity": "medium",
  "vulnerability": "AWS Metadata Exposure",
  "description": "Access to the AWS Metadata API exposes information about the machines associated with the cluster",
  "evidence": "cidr: 192.168.0.0/19",
  "avd_reference": "https://avd.aquasec.com/kube-hunter/khv053/",
  "hunter": "Host Discovery when running as pod"
}
```

## Contribution checklist
 - [ ] I have read the Contributing Guidelines.
 - [ ] The commits refer to an active issue in the repository.
 - [ ] I have added automated testing to cover this case.

2021-04-20 08:07 UTC, danielsagi requested changes
Hi @jan0ski 
That's wonderful! I've been waiting for this to be starting taken care of ever since kube-hunter started. very well done.
As you probably saw, kube-hunter's implementation for metadata discovery in azure is far from good design, and yet you managed to follow the design and implement a new feature. (Hurray!) My future plans for this is to move all cloud discovery to a differrent module, so they will have their own hunter. (see #445 ) but for now this integrates well enough and I don't see a reason to not add new features until our cloud discovery architecture change.

One thing I'll ask of you to add before I'll merge is a support for the `--quick` option. see my comments. (the implementation should be like in azure discovery) 

Thanks!

2021-04-20 08:07 UTC, danielsagi commented on kube_hunter/modules/discovery/hosts.py
> +        self.publish_event(AWSMetadataApi(cidr=cidr))
Please check of `config.quick` was set, and if so change the subnet to be "24"

2021-04-20 08:07 UTC, danielsagi commented on kube_hunter/modules/discovery/hosts.py
> +        self.publish_event(AWSMetadataApi(cidr=cidr))
Please check of `config.quick` was set, and if so change the subnet to be "24"

2021-04-20 20:37 UTC, jan0ski commented
Updated the discovery functions and the README to reflect the `--quick` option for AWS metadata as well.

2021-04-21 09:01 UTC, danielsagi reviewed
Lgtm

2021-04-21 17:54 UTC, danielsagi approved these changes

2021-04-21 17:57 UTC, merged